# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:

# 一个 workflow 由多个 jobs 组成, 并且他们可以并行运行
jobs:
  # 一个job
  build-on-linux:
    # 指定 Runer
    runs-on: ubuntu-latest

    # 当前 job 中需要执行的一系列任务
    steps:
      # Runs a set of commands using the runners shell
      - name: 执行一个脚本
        run: echo 当前时间 date
